# fly.toml app configuration file generated for trove on 2023-11-08T21:50:36-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trove"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
